### PR TITLE
Fix can not read if schema changed

### LINKED ISSUE #161: Cannot read data normally if schema is changed
When table schema is changed in MySQL client or TiDB, we experience errror in reading and retrieving data correctly.
```
scala> spark.sql("select * from a").show(truncate=false);
+-----------+--------------------+
|id_int     |id_bigint           |
+-----------+--------------------+
|-2147483648|-9223372036854775808|
+-----------+--------------------+
```

Now we do some DDL operations:
```
mysql> alter table a add column ts timestamp;
Query OK, 0 rows affected (0.27 sec)

mysql> select * from a;
+-------------+----------------------+---------------------+
| id_int      | id_bigint            | ts                  |
+-------------+----------------------+---------------------+
| -2147483648 | -9223372036854775808 | 2017-11-28 14:10:02 |
+-------------+----------------------+---------------------+
1 row in set (0.00 sec)
```

After schema changed:
```
scala> spark.sql("select * from a").show(truncate=false);
+-----------+--------------------+
|id_int     |id_bigint           |
+-----------+--------------------+
|-2147483648|-9223372036854775808|
+-----------+--------------------+
```

### LINKED ISSUE #198: Default value information not fetched
This issue is extracted from [this former issue](https://github.com/pingcap/tikv-client-lib-java/issues/161).

In the eighth floor of that issue the description of _default value not fetched_ is presented, quote, 

> More specifically, if we use alter table a add column ts int;, we can output the correct table content with a default NULL column concatenated to its end. (Well that's normal)
But if we use alter table a add column ts timestamp; to alter target table, instead we are outputting an empty table.
When we use alter table a add column ts int default 0;, the concatenated column remains NULL.

Extract this sub-issue now since it seems an independent problem.

### PR DESCRIPTION
**Pull request by zhexuany**
~~This PR should fix https://github.com/pingcap/tikv-client-lib-java/issues/161~~
This PR fixes #198 

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tikv-client-lib-java/197)

### CODE REVIEW

**Comment by zhexuany** [comment]
a few test case to verify this PR actually fixes the problem.

```
create table t1(c1 int not null);
insert into t1 value(1);
alter table t1 add column c2 int;
```
output from mysql
```
1 null
```
output from java client 
```
1 null
```

Second group 
```
alter table t1 add column s1 varchar(25);
```

output from mysql: `1 null null`
output from java client: `1 null null`

third group 
```
alter table t1 add column f1 float;
```

output from mysql: `1 null null null`
output from java client: `1 null null null`

**Comment by zhexuany** [comment]
@ilovesoup @birdstorm @Novemser PR is ready to review.

**Comment by birdstorm** [comment]
@zhexuany awesome, i will take a look

File: src/main/java/com/pingcap/tikv/Main.java [hunk 1]
```diff
@@ -1,10 +1,79 @@
...
+    ScanBuilder scanBuilder = new ScanBuilder();
+    ScanBuilder.ScanPlan scanPlan = scanBuilder.buildScan(new ArrayList<>(), table);
+    selectRequest.addRequiredColumn(TiColumnRef.create("c1", table))
+        .addRequiredColumn(TiColumnRef.create("c2", table))
+        .addRequiredColumn(TiColumnRef.create("s1", table))
+        .addRequiredColumn(TiColumnRef.create("f1", table))
+        .setStartTs(snapshot.getVersion())
+        .addRanges(scanPlan.getKeyRanges())
+        .setTableInfo(table);
+    Iterator<Row> it = snapshot.tableRead(selectRequest);
```
Comment (Novemser) [inline src/main/java/com/pingcap/tikv/Main.java:44]: `snapshot.tableRead` now only accepts a `TiDAGRequest` rather than `TiSelectRequest`, which will result in complication error when `mvn package` this PR.

File: src/main/java/com/pingcap/tikv/Main.java [hunk 2]
```diff
@@ -1,10 +1,79 @@
...
+    while (it.hasNext()) {
+      Row r = it.next();
+      SchemaInfer schemaInfer = SchemaInfer.create(selectRequest);
```
Comment (Novemser) [inline src/main/java/com/pingcap/tikv/Main.java:47]: Same reason as above.

File: src/main/java/com/pingcap/tikv/Main.java (hunk 1 above)
Comment (zhexuany) [reply src/main/java/com/pingcap/tikv/Main.java:44]: DONE.

File: src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java [hunk 3]
```diff
@@ -100,6 +111,16 @@ boolean isPrimaryKey() {
     return isPrimaryKey;
   }
 
+  public String getDefaultValue() {
+    return defaultValue;
+  }
+
+  public ByteString getOriginDefultValue() {
```
Comment (birdstorm) [inline src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java]: misspell for `getOriginDefaultValue`.

File: src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java [hunk 4]
```diff
@@ -187,6 +225,7 @@ public ColumnInfo toProto(TiTableInfo table) {
         .setColumnLen((int) type.getLength())
         .setDecimal(type.getDecimal())
         .setFlag(type.getFlag())
+        .setDefaultVal(getOriginDefultValue())
```
Comment (birdstorm) [inline src/main/java/com/pingcap/tikv/meta/TiColumnInfo.java]: same here

**Review by birdstorm — APPROVED** [review]
LGTM
